version: "3"

services:
  pg:
    image: postgres
    environment:
      POSTGRES_DB: java
      POSTGRES_USER: username
      POSTGRES_PASSWORD: passwd
      PGDATA: /var/lib/postgresql/data/pgjava
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data/pgjava

volumes:
  db-data:
